In [1]:
%load_ext autoreload
%autoreload 2

import tensorflow as tf
import numpy as np

In [2]:
a = np.arange(1, 50).reshape(7, 7)
padding = tf.constant([[2,2], [2,2]])

In [3]:
tf.pad(a, padding, 'REFLECT')

<tf.Tensor: id=2, shape=(11, 11), dtype=int64, numpy=
array([[17, 16, 15, 16, 17, 18, 19, 20, 21, 20, 19],
       [10,  9,  8,  9, 10, 11, 12, 13, 14, 13, 12],
       [ 3,  2,  1,  2,  3,  4,  5,  6,  7,  6,  5],
       [10,  9,  8,  9, 10, 11, 12, 13, 14, 13, 12],
       [17, 16, 15, 16, 17, 18, 19, 20, 21, 20, 19],
       [24, 23, 22, 23, 24, 25, 26, 27, 28, 27, 26],
       [31, 30, 29, 30, 31, 32, 33, 34, 35, 34, 33],
       [38, 37, 36, 37, 38, 39, 40, 41, 42, 41, 40],
       [45, 44, 43, 44, 45, 46, 47, 48, 49, 48, 47],
       [38, 37, 36, 37, 38, 39, 40, 41, 42, 41, 40],
       [31, 30, 29, 30, 31, 32, 33, 34, 35, 34, 33]])>

In [33]:
tf.shape(b)

<tf.Tensor: id=628, shape=(4,), dtype=int32, numpy=array([1, 7, 7, 1], dtype=int32)>

In [30]:
from layers import Conv2DReflect
conv = Conv2DReflect(filters=64, kernel_size=1, padding="SAME", strides=3)

b = np.expand_dims(a, 0)
b = np.expand_dims(b, -1)
b = b.astype(np.float32)

conv(b)

3 3
tf.Tensor(
[[0 0]
 [0 0]
 [0 0]
 [0 0]], shape=(4, 2), dtype=int32)


<tf.Tensor: id=570, shape=(1, 3, 3, 64), dtype=float32, numpy=
array([[[[ 6.51341081e-02,  2.23751068e-01,  2.66915560e-02,
          -8.69606882e-02, -2.77702332e-01, -1.07890934e-01,
           4.93606627e-02, -1.43938795e-01, -1.22172490e-01,
          -2.32017279e-01,  1.99540377e-01,  1.82122260e-01,
          -2.20392764e-01, -2.75273532e-01, -4.51666415e-02,
          -2.84308583e-01,  2.15041339e-01,  2.70420313e-01,
           2.08990395e-01,  2.11201429e-01, -2.76165962e-01,
          -1.08257905e-01,  1.31089181e-01, -7.61973113e-02,
          -1.59012243e-01,  1.80077583e-01,  2.35169291e-01,
          -2.18278617e-01, -1.41846463e-01,  5.07144928e-02,
          -1.32812217e-01,  1.15280718e-01, -2.18013361e-01,
           1.43036395e-01, -1.70335189e-01,  1.82436973e-01,
           9.23494697e-02, -1.43043697e-02, -1.99474543e-01,
           2.70486176e-01,  2.27597773e-01,  8.09693038e-02,
           2.60839283e-01,  1.69284642e-02,  2.84058869e-01,
          -5.04833460e